version: "3.1"
services:
  caching-database-service:
   container_name: caching-service
   build:
     context: ./caching database
     dockerfile: ./dockerfile
   ports:
     - 3002:3002
   devices:
     - "/dev/controller_SENSOR:/dev/controller_sensor"
   environment:
     - PYTHONUNBUFFERED=1

  valve-controller-service:
   container_name: valve-controller
   build:
     context: ./valve controller
     dockerfile: ./dockerfile
   ports:
     - 3003:3003
   devices:
     - "/dev/controller_VALVE:/dev/controller_valve"
   environment:
     - PYTHONUNBEFFERED=1

  # storage-database-service:
  #   container_name: storage-service
  #   build:
  #     context: ./storage database
  #     dockerfile: dockerfile
  #   ports:
  #     - 3004:3004
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - SSL_DISABLE=True
  #   volumes:
  #     - ./Data_files:/app/dat

  # serial-parser-service:
  #   container_name: serial-parser
  #   build:
  #     context: ./serial parser
  #     dockerfile: dockerfile
  #   ports:
  #     - 3005:3005
  #   devices:
  #     - "/dev/controller_MEGA:/dev/controller_MEGA"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - SSL_DISABLE=True

#  auxiliary-database-service:
#   container_name: auxiliary-service
#   build:
#     context: ./auxiliary database
#     dockerfile: ./dockerfile
#   ports:
#     - 3004:3004
#   devices:
#     - "/dev/controller_LOXLVL:/dev/controller_LOXLVL"
#   environment:
#     - PYTHONUNBUFFERED=1
#     - SSL_DISABLE=True

  redis-db:
    container_name: redis-database
    image: redis
    ports:
      - 6379:6379
