version: "3.1"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  #redis:
  #  image: "redis:alpine"

  caching-database-service:
    container_name: caching-service
    #network_mode: host
    build:
      context: ./EnginePythonServer/caching database
      dockerfile: dockerfile
    ports:
     - 3002:3002
    devices:
     - "/dev/controller_MEGA:/dev/controller_sensor"
    environment:
      #PYTHONUNBUFFERED: 1
      SSL_DISABLE: "True"

  storage-database-service:
    container_name: storage-service
    #network_mode: host
    build:
      context: ./EnginePythonServer/storage database
      dockerfile: dockerfile
    ports:
      - 3004:3004
    environment:
      PYTHONUNBUFFERED: 1
      SSL_DISABLE: "True"

  redis-db:
    container_name: redis-database
    image: redis
    ports:
      - 6379:6379
