version: "3.4"

services:
  valve-control-service:
    container_name: valve-control
    network_mode: host
    build:
      context: ./valve controller
      dockerfile: dockerfile
    ports:
      - 3001:3001
    devices:
      - "/dev/controller_main:/dev/controller_main"

  caching-database-service:
    container_name: caching-service
    network_mode: host
    build:
      context: ./caching database
      dockerfile: dockerfile
    ports:
      - 3002:3002
    devices:
      - "/dev/controller_sensor:/dev/controller_sensor"

  controller-status-service:
    container_name: controller-status
    network_mode: host
    build:
      context: ./controller status
      dockerfile: dockerfile
    ports:
      - 3003:3003
    devices:
      - "/dev/controller_main:/dev/controller_main"

  storage-database-service:
    container_name: storage-service
    network_mode: host
    build:
      context: ./storage database
      dockerfile: dockerfile
    ports:
      - 3004:3004

  graph-data-service:
    container_name: graph-service
    network_mode: host
    build:
      context: ./graph data
      dockerfile: dockerfile
    ports:
      - 3005:3005

  redis-db:
    container_name: redis-database
    network_mode: host
    image: redis
    ports:
      - 6379:6379
