FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 3004

CMD ["python3", "index.py", "115200", "/dev/controller_LOXLVL", "auxiliary_stream"]
